Repository GDOU-LYF/GDOUgym, pull requests merged in 2022-06, with the labels that each got.

#79 日志系统
  gym_java/src/main/java/edu/gdou/gym_java/GymJavaApplication.java
  gym_java/src/main/java/edu/gdou/gym_java/config/LogFilter.java
  gym_java/src/main/java/edu/gdou/gym_java/controller/AnnouncementController.java
  gym_java/src/main/java/edu/gdou/gym_java/exception/ExceptionAdvice.java
  gym_java/src/main/java/edu/gdou/gym_java/exception/GlobalException.java
  gym_java/src/main/java/edu/gdou/gym_java/service/serviceImpl/cm/CompetitionServiceImpl.java
  gym_java/src/main/java/edu/gdou/gym_java/shiro/MyRealm.java
  gym_java/src/main/java/edu/gdou/gym_java/shiro/jwt/JWTFilter.java
Labels: bug

#94 场地修改状态完成
  vue/src/request/api.js
  vue/src/views/site/siteArrange.vue
Labels: question

#118 场地模块
  vue/src/views/Home.vue
  vue/src/views/site/appointPay.vue
  vue/src/views/site/appointmentManagement.vue
  vue/src/views/site/siteAppointment.vue
  vue/src/views/site/siteArrange.vue
  vue/src/views/site/siteManagement.vue
Labels: duplicate
